#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Icon {
    None,
    Folder,
    FolderOpen,
    File,
    Mesh,
    Material,
    Texture,
    Light,
    Camera,
    Scene,
    Play,
    Pause,
    Stop,
    Record,
    Save,
    Open,
    New,
    Undo,
    Redo,
    Cut,
    Copy,
    Paste,
    Delete,
    Add,
    Remove,
    Settings,
    Search,
    Filter,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    ChevronRight,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    Check,
    Cross,
    Warning,
    Error,
    Info,
    Move,
    Rotate,
    Scale,
    Grid,
    Snap,
    PCG,
    Globe,
    Jobs,
    Curve,
    Quest,
    Database,
    Physics,
    Tree,
    Skeleton,
    Input,
    Water,
    Spline,
    Particles,
    Decal,
    AI,
    Anim,
    RenderGraph,
    VFX,
}

impl Icon {
    pub fn glyph(self) -> &'static str {
        match self {
            Icon::None => "",
            Icon::Folder => "[D]",
            Icon::FolderOpen => "[D-]",
            Icon::File => "[F]",
            Icon::Mesh => "[M]",
            Icon::Material => "[Mt]",
            Icon::Texture => "[T]",
            Icon::Light => "[L]",
            Icon::Camera => "[C]",
            Icon::Scene => "[S]",
            Icon::Play => ">",
            Icon::Pause => "||",
            Icon::Stop => "[]",
            Icon::Record => "(o)",
            Icon::Save => "[s]",
            Icon::Open => "[o]",
            Icon::New => "[n]",
            Icon::Undo => "<-",
            Icon::Redo => "->",
            Icon::Cut => "x|",
            Icon::Copy => "[c]",
            Icon::Paste => "[v]",
            Icon::Delete => "X",
            Icon::Add => "+",
            Icon::Remove => "-",
            Icon::Settings => "*",
            Icon::Search => "?",
            Icon::Filter => "v",
            Icon::Eye => "@",
            Icon::EyeOff => "@/",
            Icon::Lock => "#",
            Icon::Unlock => "#/",
            Icon::ChevronRight => ">",
            Icon::ChevronDown => "v",
            Icon::ChevronUp => "^",
            Icon::ChevronLeft => "<",
            Icon::Check => "v",
            Icon::Cross => "x",
            Icon::Warning => "!",
            Icon::Error => "!!",
            Icon::Info => "i",
            Icon::Move => "+",
            Icon::Rotate => "o",
            Icon::Scale => "[]",
            Icon::Grid => "#",
            Icon::Snap => ".",
            Icon::PCG => "[P]",
            Icon::Globe => "[G]",
            Icon::Jobs => "[J]",
            Icon::Curve => "~",
            Icon::Quest => "[Q]",
            Icon::Database => "[D]",
            Icon::Physics => "[Ph]",
            Icon::Tree => "[Tr]",
            Icon::Skeleton => "[Sk]",
            Icon::Input => "[In]",
            Icon::Water => "[W]",
            Icon::Spline => "[Sp]",
            Icon::Particles => "[Pt]",
            Icon::Decal => "[Dc]",
            Icon::AI => "[AI]",
            Icon::Anim => "[An]",
            Icon::RenderGraph => "[Rg]",
            Icon::VFX => "[Vx]",
        }
    }
}
