#[derive(Copy, Clone, Debug)]
pub struct Metrics {
    pub menu_bar_height: f64,
    pub tool_bar_height: f64,
    pub status_bar_height: f64,
    pub tab_height: f64,
    pub title_bar_height: f64,
    pub button_height: f64,
    pub slider_height: f64,
    pub row_height: f64,
    pub indent_step: f64,
    pub padding: f64,
    pub padding_small: f64,
    pub spacing: f64,
    pub border_width: f64,
    pub splitter_thickness: f64,
    pub corner_radius: f64,
    pub corner_radius_small: f64,
    pub shadow_spread: f64,
    pub scroll_bar_width: f64,
    pub icon_size: f64,
    pub font_size_small: f64,
    pub font_size_normal: f64,
    pub font_size_large: f64,
    pub tooltip_delay_ms: f64,
}

impl Metrics {
    pub const DEFAULT: Self = Self {
        menu_bar_height: 28.0,
        tool_bar_height: 38.0,
        status_bar_height: 24.0,
        tab_height: 28.0,
        title_bar_height: 26.0,
        button_height: 26.0,
        slider_height: 18.0,
        row_height: 24.0,
        indent_step: 14.0,
        padding: 10.0,
        padding_small: 6.0,
        spacing: 6.0,
        border_width: 1.0,
        splitter_thickness: 4.0,
        corner_radius: 8.0,
        corner_radius_small: 4.0,
        shadow_spread: 14.0,
        scroll_bar_width: 12.0,
        icon_size: 16.0,
        font_size_small: 11.0,
        font_size_normal: 13.0,
        font_size_large: 16.0,
        tooltip_delay_ms: 500.0,
    };

    pub const COMPACT: Self = Self {
        menu_bar_height: 22.0,
        tool_bar_height: 30.0,
        status_bar_height: 20.0,
        tab_height: 24.0,
        title_bar_height: 22.0,
        button_height: 22.0,
        slider_height: 14.0,
        row_height: 20.0,
        indent_step: 12.0,
        padding: 7.0,
        padding_small: 4.0,
        spacing: 4.0,
        border_width: 1.0,
        splitter_thickness: 3.0,
        corner_radius: 6.0,
        corner_radius_small: 3.0,
        shadow_spread: 10.0,
        scroll_bar_width: 10.0,
        icon_size: 14.0,
        font_size_small: 10.0,
        font_size_normal: 11.0,
        font_size_large: 14.0,
        tooltip_delay_ms: 500.0,
    };
}
